wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.31
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.8
layer_1:
  desc: null
  value: 32
layer_2:
  desc: null
  value: 99
lr:
  desc: null
  value: 0.7060830900028868
momentum:
  desc: null
  value: 0.7998580517636386
no_epoch:
  desc: null
  value: 3971
weight_decay:
  desc: null
  value: 0.006272511920408896
