wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.31
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.8
layer_1:
  desc: null
  value: 65
layer_2:
  desc: null
  value: 10
lr:
  desc: null
  value: 0.48092090532118514
momentum:
  desc: null
  value: 0.9884132225302366
no_epoch:
  desc: null
  value: 1492
weight_decay:
  desc: null
  value: 0.08621977819690507
