wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.31
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.8
layer_1:
  desc: null
  value: 74
layer_2:
  desc: null
  value: 159
lr:
  desc: null
  value: 0.7718307109930564
momentum:
  desc: null
  value: 0.997323027386784
no_epoch:
  desc: null
  value: 4528
weight_decay:
  desc: null
  value: 0.004788943857913619
