wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.31
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.8
layer_1:
  desc: null
  value: 15
layer_2:
  desc: null
  value: 30
lr:
  desc: null
  value: 0.40159537872379114
momentum:
  desc: null
  value: 0.9330143923104154
no_epoch:
  desc: null
  value: 4920
weight_decay:
  desc: null
  value: 0.4583262963132294
