wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.31
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.8
activation:
  desc: null
  value: 1
layer_1:
  desc: null
  value: 88
layer_2:
  desc: null
  value: 27
lr:
  desc: null
  value: 0.6529121100097708
no_epoch:
  desc: null
  value: 3090
