wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.31
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.8
layer_1:
  desc: null
  value: 82
layer_2:
  desc: null
  value: 12
lr:
  desc: null
  value: 0.8358306320339909
momentum:
  desc: null
  value: 0.7174977704169676
no_epoch:
  desc: null
  value: 3986
weight_decay:
  desc: null
  value: 0.8979300829642303
