wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.31
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.8
layer_1:
  desc: null
  value: 12
layer_2:
  desc: null
  value: 22
lr:
  desc: null
  value: 0.004854604469898716
momentum:
  desc: null
  value: 0.8885579695623015
no_epoch:
  desc: null
  value: 1182
weight_decay:
  desc: null
  value: 0.07976634172756136
