wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.31
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.8
layer_1:
  desc: null
  value: 182
layer_2:
  desc: null
  value: 160
lr:
  desc: null
  value: 0.366083280794154
momentum:
  desc: null
  value: 0.1749363047174327
no_epoch:
  desc: null
  value: 2382
weight_decay:
  desc: null
  value: 0.41056150621470144
