wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.31
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.8
layer_1:
  desc: null
  value: 33
layer_2:
  desc: null
  value: 45
lr:
  desc: null
  value: 0.27538719022623814
momentum:
  desc: null
  value: 0.9065907265547418
no_epoch:
  desc: null
  value: 1822
weight_decay:
  desc: null
  value: 0.041288143510788355
