wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.31
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.8
layer_1:
  desc: null
  value: 13
layer_2:
  desc: null
  value: 138
lr:
  desc: null
  value: 0.39420044641668994
momentum:
  desc: null
  value: 0.9915920880404501
no_epoch:
  desc: null
  value: 4304
weight_decay:
  desc: null
  value: 0.011706212877132582
