wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.31
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.8
layer_1:
  desc: null
  value: 16
layer_2:
  desc: null
  value: 114
lr:
  desc: null
  value: 0.05585516229034493
momentum:
  desc: null
  value: 0.9838517254042997
no_epoch:
  desc: null
  value: 1870
weight_decay:
  desc: null
  value: 0.181796533797266
