wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.31
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.8
layer_1:
  desc: null
  value: 16
layer_2:
  desc: null
  value: 59
lr:
  desc: null
  value: 0.15763901890164322
momentum:
  desc: null
  value: 0.847926880721694
no_epoch:
  desc: null
  value: 4791
weight_decay:
  desc: null
  value: 0.0343029795872718
