wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.31
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.8
activation:
  desc: null
  value: 1
layer_1:
  desc: null
  value: 39
layer_2:
  desc: null
  value: 70
lr:
  desc: null
  value: 0.8491908298129413
no_epoch:
  desc: null
  value: 3602
