wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.31
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.8
activation:
  desc: null
  value: 1
layer_1:
  desc: null
  value: 13
layer_2:
  desc: null
  value: 20
lr:
  desc: null
  value: 0.27078224584790145
no_epoch:
  desc: null
  value: 4854
