wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.31
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.8
layer_1:
  desc: null
  value: 14
layer_2:
  desc: null
  value: 79
lr:
  desc: null
  value: 0.9125632931306537
momentum:
  desc: null
  value: 0.8042377698520086
no_epoch:
  desc: null
  value: 684
weight_decay:
  desc: null
  value: 0.07660495053058192
