wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.31
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.8
layer_1:
  desc: null
  value: 22
layer_2:
  desc: null
  value: 169
lr:
  desc: null
  value: 0.5304106586123484
momentum:
  desc: null
  value: 0.8437790202334657
no_epoch:
  desc: null
  value: 1954
weight_decay:
  desc: null
  value: 0.02913637540482461
