wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.31
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.8
layer_1:
  desc: null
  value: 83
layer_2:
  desc: null
  value: 11
lr:
  desc: null
  value: 0.14986065074186228
momentum:
  desc: null
  value: 0.8642225023334346
no_epoch:
  desc: null
  value: 1175
weight_decay:
  desc: null
  value: 0.025440187176347884
