wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.31
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.8
layer_1:
  desc: null
  value: 150
layer_2:
  desc: null
  value: 149
lr:
  desc: null
  value: 0.9417469458229958
momentum:
  desc: null
  value: 0.5144395847452718
no_epoch:
  desc: null
  value: 1682
weight_decay:
  desc: null
  value: 0.9847881704768312
